### ISSUE TITLE
Ventura, Operation not permitted

### ISSUE THREAD

**Issue by ShawnBaek** [iGhibli/iOS-DeviceSupport#206]
I followed this [guide](https://github.com/iGhibli/iOS-DeviceSupport/issues/177)

sudo python3 ./deploy.py

I got an error like this. 

Anyone facing this issue? Can you share how did you resolve it?

```bash
Unzip file "13.2(FromXcode11.3(11C29)).zip" to /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport
Traceback (most recent call last):
  File "/Users/sungwookbaek/Projects/deviceSupport/iOS-DeviceSupport/./deploy.py", line 46, in <module>
    process(args.target, args.version)
  File "/Users/sungwookbaek/Projects/deviceSupport/iOS-DeviceSupport/./deploy.py", line 26, in process
    unzip_file(i, target)
  File "/Users/sungwookbaek/Projects/deviceSupport/iOS-DeviceSupport/./deploy.py", line 12, in unzip_file
    zip_ref.extractall(target)
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/zipfile.py", line 1645, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/zipfile.py", line 1699, in _extract_member
    open(targetpath, "wb") as target:
PermissionError: [Errno 1] Operation not permitted: '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport/13.2/DeveloperDiskImage.dmg.signature'
```

**Comment by antonanders** [comment]
Hey, I'm facing the same issue. 
What you can do to have a workaround for now is simply extract your desired version manually using finder. Then go to Applications --> right click on Xcode --> show package content and navigate to ```/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport```.

Here you can paste your e.g. 16.4 folder you previously extracted. 
Restart Xcode, you should be done.
